 server {
        listen 8089;
        listen [::]:8089;

        server_name 172.25.205.142;

        root /var/www/devops-hackathon-de002-dangquoctoan/src;
        index index.html;

        access_log /var/log/nginx/dangquoctoan-k24cntt1.access.log;
        error_log /var/log/nginx/dangquoctoan-k24cntt1.error.log;

        location / {
            allow all;
            try_files $uri $uri/ =404;
        }
    }